[package]
name = "simulation_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = { version = "0.7.1", default-features = false, features = [
    "graphmap",
] }
strum = { version = "0.27.1", default-features = false, features = ["derive"] }
